Update [dbo].[CommonCode] Set NumValue2 = 0 Where CommonId = 'DeCuong-1'
Update [dbo].[CommonCode] Set NumValue2 = 0 Where CommonId = 'Introduction-1'
Update [dbo].[CommonCode] Set NumValue2 = 0 Where CommonId = 'Introduction-2'
Update [dbo].[CommonCode] Set NumValue2 = 0 Where CommonId = 'Introduction-3'
Update [dbo].[CommonCode] Set NumValue2 = 0 Where CommonId = 'Introduction-4'
Update [dbo].[CommonCode] Set NumValue2 = 0 Where CommonId = 'Introduction-5'
Update [dbo].[CommonCode] Set NumValue2 = 0 Where CommonId = 'Introduction-6'
Update [dbo].[CommonCode] Set NumValue2 = 0 Where CommonId = 'Introduction-7'
Update [dbo].[CommonCode] Set NumValue2 = 0 Where CommonId = 'Introduction-8'
Update [dbo].[CommonCode] Set NumValue2 = 0 Where CommonId = 'Introduction-9'
Update [dbo].[CommonCode] Set NumValue2 = 0 Where CommonId = 'Announcement-1'
Update [dbo].[CommonCode] Set NumValue2 = 0 Where CommonId = 'Announcement-2'
Update [dbo].[CommonCode] Set NumValue2 = 1 Where CommonId = 'Announcement-3'
Update [dbo].[CommonCode] Set NumValue2 = 0 Where CommonId = 'Announcement-3-1'
Update [dbo].[CommonCode] Set NumValue2 = 0 Where CommonId = 'Announcement-3-2'
Update [dbo].[CommonCode] Set StrValue2 = 'Index', NumValue2 = 1 Where CommonId = 'English-1'
Update [dbo].[CommonCode] Set StrValue2 = 'Index', NumValue2 = 0 Where CommonId = 'English-1-1'
Update [dbo].[CommonCode] Set StrValue2 = 'Index', NumValue2 = 0 Where CommonId = 'English-1-2'
Update [dbo].[CommonCode] Set StrValue2 = 'Index', NumValue2 = 0 Where CommonId = 'English-1-3'
Update [dbo].[CommonCode] Set StrValue2 = 'Index', NumValue2 = 0 Where CommonId = 'English-1-4'
Update [dbo].[CommonCode] Set StrValue2 = 'Index', NumValue2 = 0 Where CommonId = 'English-1-5'
Update [dbo].[CommonCode] Set StrValue2 = 'Index', NumValue2 = 0 Where CommonId = 'English-1-6'
Update [dbo].[CommonCode] Set StrValue2 = 'Index', NumValue2 = 0 Where CommonId = 'English-1-7'
Update [dbo].[CommonCode] Set StrValue2 = 'Index', NumValue2 = 0 Where CommonId = 'English-2'
Update [dbo].[CommonCode] Set StrValue2 = 'Index', NumValue2 = 0 Where CommonId = 'English-3'
Update [dbo].[CommonCode] Set StrValue2 = 'Index', NumValue2 = 0 Where CommonId = 'English-4'
Update [dbo].[CommonCode] Set StrValue2 = 'Index', NumValue2 = 0 Where CommonId = 'English-5'
Update [dbo].[CommonCode] Set StrValue2 = 'Index', NumValue2 = 0 Where CommonId = 'English-6'
Update [dbo].[CommonCode] Set StrValue2 = 'Index', NumValue2 = 0 Where CommonId = 'JapaneseStudies-1'
Update [dbo].[CommonCode] Set StrValue2 = 'Index', NumValue2 = 0 Where CommonId = 'JapaneseStudies-2'
Update [dbo].[CommonCode] Set StrValue2 = 'Index', NumValue2 = 0 Where CommonId = 'JapaneseStudies-3'
Update [dbo].[CommonCode] Set StrValue2 = 'Index', NumValue2 = 0 Where CommonId = 'JapaneseStudies-4'
Update [dbo].[CommonCode] Set NumValue2 = 0 Where CommonId = 'Dashboard'
Update [dbo].[CommonCode] Set NumValue2 = 0 Where CommonId = 'Footer'
Update [dbo].[CommonCode] Set NumValue2 = 0 Where CommonId = 'SlideShow'
Update [dbo].[CommonCode] Set NumValue2 = 0 Where CommonId = 'SocialNetwork'
Update [dbo].[CommonCode] Set NumValue2 = 0 Where CommonId = 'TopBar'
Update [dbo].[CommonCode] Set NumValue2 = 0 Where CommonId = 'Comment'
Update [dbo].[CommonCode] Set NumValue2 = 0 Where CommonId = 'Content'
Update [dbo].[CommonCode] Set NumValue2 = 0 Where CommonId = 'ImagesClass'

