---DELETE FOREIGN KEY
ALTER TABLE [dbo].[Class] DROP CONSTRAINT [FK_Class_Course] 
GO
-- DELETE COLUMN COURSEID
ALTER TABLE [dbo].[Class] DROP COLUMN [CourseId]
GO
-- ADD COULUMN STARTDATE AND ENDDATE
ALTER TABLE [dbo].[Class] ADD StartDate DateTime
GO
ALTER TABLE [dbo].[Class] ADD EndDate DateTime
GO
ALTER TABLE [dbo].[Class] ADD Images varchar(255)
GO

-- INSERT CONTENTS
INSERT [dbo].[Class] ( [Code], [Name], [SubjectId], [Status], [VenueId], [Description], [Prerequisition], [TeacherId], [TeachingAssistantId], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [StartDate], [EndDate], [Images]) VALUES ( N'Code1', N'English Phonetics and Phonology', NULL, N'ACT', 10, N'Academic English Program focus on improving language skills and academic skills, help students have enough strength to be able to learn successfully in an academic environment speak English.', N'Intermediate English', 1, N'2;3;', N'Administrator', CAST(N'2017-01-04 00:00:00.000' AS DateTime), N'Administrator', CAST(N'2017-01-04 00:00:00.000' AS DateTime), CAST(N'2017-01-04 00:00:00.000' AS DateTime), CAST(N'2017-05-04 00:00:00.000' AS DateTime), N'PhoneticsandPhonology.jpg')
INSERT [dbo].[Class] ( [Code], [Name], [SubjectId], [Status], [VenueId], [Description], [Prerequisition], [TeacherId], [TeachingAssistantId], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [StartDate], [EndDate], [Images]) VALUES ( N'Code2', N'Morphology – Syntax', NULL, N'ACT', 10, N'1Academic English Program focus on improving language skills and academic skills, help students have enough strength to be able to learn successfully in an academic environm1ent speak English.', N'Intermediate English', 1, N'2;3;', N'Administrator', CAST(N'2017-01-04 00:00:00.000' AS DateTime), N'Administrator', CAST(N'2017-01-04 00:00:00.000' AS DateTime), CAST(N'2017-01-04 00:00:00.000' AS DateTime), CAST(N'2017-05-04 00:00:00.000' AS DateTime), N'MorphologySyntax.jpg')
INSERT [dbo].[Class] ( [Code], [Name], [SubjectId], [Status], [VenueId], [Description], [Prerequisition], [TeacherId], [TeachingAssistantId], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [StartDate], [EndDate], [Images]) VALUES ( N'Code3', N'Discourse Analysis', NULL, N'ACT', 10, N'2Academic English Program focus on improving language skills and academic skills, help students have enough strength to be able to learn successfully in an academic environment speak English.', N'Intermediate English', 1, N'2;3;', N'Administrator', CAST(N'2017-01-04 00:00:00.000' AS DateTime), N'Administrator', CAST(N'2017-01-04 00:00:00.000' AS DateTime), CAST(N'2017-01-04 00:00:00.000' AS DateTime), CAST(N'2017-05-04 00:00:00.000' AS DateTime), N'semantics.jpg')
INSERT [dbo].[Class] ( [Code], [Name], [SubjectId], [Status], [VenueId], [Description], [Prerequisition], [TeacherId], [TeachingAssistantId], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [StartDate], [EndDate], [Images]) VALUES ( N'Code4', N'Semantics', NULL, N'ACT', 10, N'Academic English Program focus on improving language skills and academic skills, help students have enough strength to be able to learn successfully in an academic environment speak English.', N'Intermediate English', 1, N'2;3;', N'Administrator', CAST(N'2017-01-04 00:00:00.000' AS DateTime), N'Administrator', CAST(N'2017-01-04 00:00:00.000' AS DateTime), CAST(N'2017-01-04 00:00:00.000' AS DateTime), CAST(N'2017-05-04 00:00:00.000' AS DateTime), N'DiscourseAnalysis.jpg')
INSERT [dbo].[Class] ( [Code], [Name], [SubjectId], [Status], [VenueId], [Description], [Prerequisition], [TeacherId], [TeachingAssistantId], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [StartDate], [EndDate], [Images]) VALUES ( N'Code5', N'Second Language Acquisition PG', NULL, N'ACT', 10, N'1Academic English Program focus on improving language skills and academic skills, help students have enough strength to be able to learn successfully in an academic environm1ent speak English.', N'Intermediate English', 1, N'2;3;', N'Administrator', CAST(N'2017-01-04 00:00:00.000' AS DateTime), N'Administrator', CAST(N'2017-01-04 00:00:00.000' AS DateTime), CAST(N'2017-01-04 00:00:00.000' AS DateTime), CAST(N'2017-05-04 00:00:00.000' AS DateTime), N'image3.png')
INSERT [dbo].[Class] ( [Code], [Name], [SubjectId], [Status], [VenueId], [Description], [Prerequisition], [TeacherId], [TeachingAssistantId], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [StartDate], [EndDate], [Images]) VALUES ( N'Code6', N'English Phonetics and Phonology PG', NULL, N'ACT', 10, N'2Academic English Program focus on improving language skills and academic skills, help students have enough strength to be able to learn successfully in an academic environment speak English.', N'Intermediate English', 1, N'2;3;', N'Administrator', CAST(N'2017-01-04 00:00:00.000' AS DateTime), N'Administrator', CAST(N'2017-01-04 00:00:00.000' AS DateTime), CAST(N'2017-01-04 00:00:00.000' AS DateTime), CAST(N'2017-05-04 00:00:00.000' AS DateTime), N'images.png')
INSERT [dbo].[Class] ( [Code], [Name], [SubjectId], [Status], [VenueId], [Description], [Prerequisition], [TeacherId], [TeachingAssistantId], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [StartDate], [EndDate], [Images]) VALUES ( N'Code7', N'Linguistics PG', NULL, N'ACT', 10, N'2Academic English Program focus on improving language skills and academic skills, help students have enough strength to be able to learn successfully in an academic environment speak English.', N'Intermediate English', 1, N'2;3;', N'Administrator', CAST(N'2017-01-04 00:00:00.000' AS DateTime), N'Administrator', CAST(N'2017-01-04 00:00:00.000' AS DateTime), CAST(N'2017-01-04 00:00:00.000' AS DateTime), CAST(N'2017-05-04 00:00:00.000' AS DateTime), N'images.jpg')


INSERT [dbo].[Class] ( [Code], [Name], [SubjectId], [Status], [VenueId], [Description], [Prerequisition], [TeacherId], [TeachingAssistantId], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [StartDate], [EndDate], [Images]) VALUES ( N'Code8', N'English Phonetics and Phonology', NULL, N'ACT', 10, N'Academic English Program focus on improving language skills and academic skills, help students have enough strength to be able to learn successfully in an academic environment speak English.', N'Intermediate English', 1, N'2;3;', N'Administrator', CAST(N'2017-01-04 00:00:00.000' AS DateTime), N'Administrator', CAST(N'2017-01-04 00:00:00.000' AS DateTime), CAST(N'2017-01-04 00:00:00.000' AS DateTime), CAST(N'2017-01-04 00:00:00.000' AS DateTime), N'PhoneticsandPhonology.jpg')
INSERT [dbo].[Class] ( [Code], [Name], [SubjectId], [Status], [VenueId], [Description], [Prerequisition], [TeacherId], [TeachingAssistantId], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [StartDate], [EndDate], [Images]) VALUES ( N'Code9', N'Morphology – Syntax', NULL, N'ACT', 10, N'1Academic English Program focus on improving language skills and academic skills, help students have enough strength to be able to learn successfully in an academic environm1ent speak English.', N'Intermediate English', 1, N'2;3;', N'Administrator', CAST(N'2017-01-04 00:00:00.000' AS DateTime), N'Administrator', CAST(N'2017-01-04 00:00:00.000' AS DateTime), CAST(N'2017-01-04 00:00:00.000' AS DateTime), CAST(N'2017-01-04 00:00:00.000' AS DateTime), N'MorphologySyntax.jpg')
INSERT [dbo].[Class] ( [Code], [Name], [SubjectId], [Status], [VenueId], [Description], [Prerequisition], [TeacherId], [TeachingAssistantId], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [StartDate], [EndDate], [Images]) VALUES ( N'Code10', N'Discourse Analysis', NULL, N'ACT', 10, N'2Academic English Program focus on improving language skills and academic skills, help students have enough strength to be able to learn successfully in an academic environment speak English.', N'Intermediate English', 1, N'2;3;', N'Administrator', CAST(N'2017-01-04 00:00:00.000' AS DateTime), N'Administrator', CAST(N'2017-01-04 00:00:00.000' AS DateTime), CAST(N'2017-01-04 00:00:00.000' AS DateTime), CAST(N'2017-01-04 00:00:00.000' AS DateTime), N'semantics.jpg')
INSERT [dbo].[Class] ( [Code], [Name], [SubjectId], [Status], [VenueId], [Description], [Prerequisition], [TeacherId], [TeachingAssistantId], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [StartDate], [EndDate], [Images]) VALUES ( N'Code11', N'Semantics', NULL, N'ACT', 10, N'Academic English Program focus on improving language skills and academic skills, help students have enough strength to be able to learn successfully in an academic environment speak English.', N'Intermediate English', 1, N'2;3;', N'Administrator', CAST(N'2017-01-04 00:00:00.000' AS DateTime), N'Administrator', CAST(N'2017-01-04 00:00:00.000' AS DateTime), CAST(N'2017-01-04 00:00:00.000' AS DateTime), CAST(N'2017-01-04 00:00:00.000' AS DateTime), N'DiscourseAnalysis.jpg')
INSERT [dbo].[Class] ( [Code], [Name], [SubjectId], [Status], [VenueId], [Description], [Prerequisition], [TeacherId], [TeachingAssistantId], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [StartDate], [EndDate], [Images]) VALUES ( N'Code12', N'Second Language Acquisition PG', NULL, N'ACT', 10, N'1Academic English Program focus on improving language skills and academic skills, help students have enough strength to be able to learn successfully in an academic environm1ent speak English.', N'Intermediate English', 1, N'2;3;', N'Administrator', CAST(N'2017-01-04 00:00:00.000' AS DateTime), N'Administrator', CAST(N'2017-01-04 00:00:00.000' AS DateTime), CAST(N'2017-01-04 00:00:00.000' AS DateTime), CAST(N'2017-01-04 00:00:00.000' AS DateTime), N'image3.png')
INSERT [dbo].[Class] ( [Code], [Name], [SubjectId], [Status], [VenueId], [Description], [Prerequisition], [TeacherId], [TeachingAssistantId], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [StartDate], [EndDate], [Images]) VALUES ( N'Code13', N'English Phonetics and Phonology PG', NULL, N'ACT', 10, N'2Academic English Program focus on improving language skills and academic skills, help students have enough strength to be able to learn successfully in an academic environment speak English.', N'Intermediate English', 1, N'2;3;', N'Administrator', CAST(N'2017-01-04 00:00:00.000' AS DateTime), N'Administrator', CAST(N'2017-01-04 00:00:00.000' AS DateTime), CAST(N'2017-01-04 00:00:00.000' AS DateTime), CAST(N'2017-01-04 00:00:00.000' AS DateTime), N'images.png')
INSERT [dbo].[Class] ( [Code], [Name], [SubjectId], [Status], [VenueId], [Description], [Prerequisition], [TeacherId], [TeachingAssistantId], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [StartDate], [EndDate], [Images]) VALUES ( N'Code14', N'Linguistics PG', NULL, N'ACT', 10, N'2Academic English Program focus on improving language skills and academic skills, help students have enough strength to be able to learn successfully in an academic environment speak English.', N'Intermediate English', 1, N'2;3;', N'Administrator', CAST(N'2017-01-04 00:00:00.000' AS DateTime), N'Administrator', CAST(N'2017-01-04 00:00:00.000' AS DateTime), CAST(N'2017-01-04 00:00:00.000' AS DateTime), CAST(N'2017-01-04 00:00:00.000' AS DateTime), N'images.jpg')
