Alter table [dbo].[TeacherMemory]
Add Type varchar(200), BackgroundId varchar(10)
Go
Alter table [dbo].[TeacherMemory]
Add BackgroundId varchar(10)
Go
ALTER TABLE [dbo].[TeacherMemory]
ADD CONSTRAINT fk_teachermemory_teacherbackground FOREIGN KEY (BackgroundId) REFERENCES teacherbackground(Id)
Go
ALTER TABLE [dbo].[TeacherStudies]
DROP COLUMN [StartDate], [EndDate]
Go
Alter table [dbo].[TeacherStudies]
Add Year varchar(10)
Go
Alter table [dbo].[TeacherResearchWork]
Add [Title] nvarchar(1000)
Go
USE [LSDB]
GO
INSERT [dbo].[TeacherBackground] ([Id], [TeacherId], [Title], [Description], [Type], [Status], [CanDelete], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (N'1', 1, N'BA of English - University of Pedagogy', N' <strong class="accent-color">
                                            English Linguistics
                                        </strong>
                                        is a university specializing in tertiary-level training of teachers and lecturers located in District 5. The university was founded as the Saigon National Pedagogical University in 1957 and reestablished by prime ministerial decree in 1976.
                                        In 1995, the university was incorporated in Ho Chi Minh City National University, but it was split to become an autonomous university with the current name in 1999.
                                        Between 1976 and 2006, the university educated 65,945 graduates, of which 1,000 were postgraduates. The university also offered training for 33,800 teachers and has education cooperations with over 50 universities worldwide.', N'EducationBackground', N'ACT', 0, N'admin', CAST(N'2017-03-10 16:25:00.000' AS DateTime), NULL, NULL)
INSERT [dbo].[TeacherBackground] ([Id], [TeacherId], [Title], [Description], [Type], [Status], [CanDelete], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (N'2', 1, N'BA of Oriental Studies – The Studies of Japan – University of Social Sciences and Humanities', N'<strong class="accent-color">
                                            Ho Chi Minh City University of Social Sciences and Humanities
                                        </strong>
                                        (Abbreviation: HCMUSSH, Vietnamese: Đại học Khoa học xã hội và Nhân văn Thành phố Hồ Chí Minh) is one of the member universities of Vietnam National University, Ho Chi Minh City, which includes the HCMUSSH, the University of Natural Sciences, the University of Technology, the International University, the University of Computer Science and the University of Economics and Law. The HCMUSSH plays an important role in Vietnam''s higher education, especially in the fields of social sciences and humanities.', N'EducationBackground', N'ACT', 0, N'admin', CAST(N'2017-03-10 16:25:00.000' AS DateTime), NULL, NULL)
INSERT [dbo].[TeacherBackground] ([Id], [TeacherId], [Title], [Description], [Type], [Status], [CanDelete], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (N'3', 1, N'MA of TESOL – Victoria University – Australia', N' <strong class="accent-color">
                                            Victoria University (VU)
                                        </strong>
                                        is a university based in Melbourne, Australia. It is a dual-sector tertiary institution providing courses in both higher education and Technical and Further Education (TAFE). 2016 marks VU''s centenary as an educational institution and its 25th anniversary as a university.
                                        VU is ranked in the world’s top 2% (THE World University Rankings 2016/2017) and firmly positioned in the QS World University Rankings 2016/2017.', N'EducationBackground', N'ACT', 0, N'admin', CAST(N'2017-03-10 16:25:00.000' AS DateTime), NULL, NULL)
INSERT [dbo].[TeacherBackground] ([Id], [TeacherId], [Title], [Description], [Type], [Status], [CanDelete], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (N'4', 1, N'PhD of English Language and Literature – Atlantic International University – USA', N'<strong class="accent-color">
                                            Atlantic International University
                                        </strong>
                                        is an American private non-profit distance education institution of higher and continuing education in Virginia Beach, Virginia. The university is associated with Edgar Cayce''s Association for Research and Enlightenment (A.R.E.) and its administrative offices are in the Don and Nancy de Laski Education Center on the main A.R.E. campus. The university is nationally accredited by the Distance Education Accrediting Commission (DEAC), which is a member of the Council for Higher Education Accreditation (CHEA), for its distance education and hybrid programs. The university also maintains licensure with the State Council of Higher Education for Virginia (SCHEV).', N'EducationBackground', N'ACT', 0, N'admin', CAST(N'2017-03-10 16:25:00.000' AS DateTime), NULL, NULL)
INSERT [dbo].[TeacherBackground] ([Id], [TeacherId], [Title], [Description], [Type], [Status], [CanDelete], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (N'5', 1, N'PhD of Comparative Linguistics – University of Social Sciences and Humanities
                                            Department of English Linguistics', N'<strong class="accent-color">
                                            English Linguistics
                                        </strong>
                                        teaching in USSH is an honor for me.
                                        Currently, the University of Social Sciences and Humanities has more than 890 faculty members and non-teaching staff.
                                        The percentage of the academic staff holding professorial titles or postgraduate degrees is 98.4 %.
                                        There are more than 22,000 students enrolled in 28 undergraduate programs,
                                        38 postgraduate programs and over 10 joint programs in collaboration with
                                        international partners. The programs offer students access to a very diverse selection of academic options from which
                                        to choose, and enhance students’ capabilities to embrace the challenge of the country’s
                                        modernization and industrialization,
                                        translating what they learn into professional achievements.', N'EducationBackground', N'ACT', 0, N'admin', CAST(N'2017-03-10 16:25:00.000' AS DateTime), NULL, NULL)
INSERT [dbo].[TeacherBackground] ([Id], [TeacherId], [Title], [Description], [Type], [Status], [CanDelete], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (N'6', 1, N'LECTURER', N'<strong class="accent-color">
                                            Lecturer
                                        </strong>
                                        for Nation University', N'CurrentJob', N'ACT', 0, N'admin', CAST(N'2017-03-10 16:25:00.000' AS DateTime), NULL, NULL)

Update [dbo].[Teacher]
Set[Description]= N' <p>I am a PhD of Comparative Linguistics in Department of English Linguistics at University of Social Sciences and Humanities – Vietnam National University Ho Chi Minh City.</p>
                    <p>Education is the mission that I have done. I have attached a full life with the word "Education", so even though in any circumstance I always want to bring education to everyone.</p>
                    <p>I had a lot of years in education and I think they need to do more now to be able to bring education to everyone.</p>
                    <p>Teaching through many universities I feel that students now are less confident in himself and his destiny betting on a scalar.</p>
                    <p>I hope the courses that I was directly taught will help students better Vietnam.</p>'
Where Id = '1'
Go
INSERT [dbo].[TeacherMemory] ([Id], [TeacherId], [Type], [URL], [FileExtension], [FileName], [UploadedBy], [UploadedDate], [Status], [CanDelete], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [BackgroundId]) VALUES (1, 1, N'Avartar', N'/Content/images/thanhdieu/', N'.jpg', N'thanhdieu-1', NULL, NULL, N'ACT', 0, N'admin', CAST(N'2017-03-10 16:25:00.000' AS DateTime), NULL, NULL, NULL)
INSERT [dbo].[TeacherMemory] ([Id], [TeacherId], [Type], [URL], [FileExtension], [FileName], [UploadedBy], [UploadedDate], [Status], [CanDelete], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [BackgroundId]) VALUES (2, 1, N'Avartar', N'/Content/images/thanhdieu/', N'.jpg', N'thanhdieu-2', NULL, NULL, N'ACT', 0, N'admin', CAST(N'2017-03-10 16:25:00.000' AS DateTime), NULL, NULL, NULL)
INSERT [dbo].[TeacherMemory] ([Id], [TeacherId], [Type], [URL], [FileExtension], [FileName], [UploadedBy], [UploadedDate], [Status], [CanDelete], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [BackgroundId]) VALUES (3, 1, N'Avartar', N'/Content/images/thanhdieu/', N'.jpg', N'thanhdieu-3', NULL, NULL, N'ACT', 0, N'admin', CAST(N'2017-03-10 16:25:00.000' AS DateTime), NULL, NULL, NULL)
INSERT [dbo].[TeacherMemory] ([Id], [TeacherId], [Type], [URL], [FileExtension], [FileName], [UploadedBy], [UploadedDate], [Status], [CanDelete], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [BackgroundId]) VALUES (4, 1, N'EducationBackground', N'/Content/images/about/', N'.png', N'supham', NULL, NULL, N'ACT', 0, N'admin', CAST(N'2017-03-10 16:25:00.000' AS DateTime), NULL, NULL, N'1')
INSERT [dbo].[TeacherMemory] ([Id], [TeacherId], [Type], [URL], [FileExtension], [FileName], [UploadedBy], [UploadedDate], [Status], [CanDelete], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [BackgroundId]) VALUES (5, 1, N'EducationBackground', N'/Content/images/about/', N'.png', N'khxhnv-logo-english', NULL, NULL, N'ACT', 0, N'admin', CAST(N'2017-03-10 16:25:00.000' AS DateTime), NULL, NULL, N'2')
INSERT [dbo].[TeacherMemory] ([Id], [TeacherId], [Type], [URL], [FileExtension], [FileName], [UploadedBy], [UploadedDate], [Status], [CanDelete], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [BackgroundId]) VALUES (6, 1, N'EducationBackground', N'/Content/images/about/', N'.png', N'khxhnv-logo-english', NULL, NULL, N'ACT', 0, N'admin', CAST(N'2017-03-10 16:25:00.000' AS DateTime), NULL, NULL, N'5')
INSERT [dbo].[TeacherMemory] ([Id], [TeacherId], [Type], [URL], [FileExtension], [FileName], [UploadedBy], [UploadedDate], [Status], [CanDelete], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [BackgroundId]) VALUES (7, 1, N'EducationBackground', N'/Content/images/about/', N'.jpg', N'victoria', NULL, NULL, N'ACT', 0, N'admin', CAST(N'2017-03-10 16:25:00.000' AS DateTime), NULL, NULL, N'3')
INSERT [dbo].[TeacherMemory] ([Id], [TeacherId], [Type], [URL], [FileExtension], [FileName], [UploadedBy], [UploadedDate], [Status], [CanDelete], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [BackgroundId]) VALUES (8, 1, N'EducationBackground', N'/Content/images/about/', N'.jpg', N'aiu', NULL, NULL, N'ACT', 0, N'admin', CAST(N'2017-03-10 16:25:00.000' AS DateTime), NULL, NULL, N'4')
INSERT [dbo].[TeacherMemory] ([Id], [TeacherId], [Type], [URL], [FileExtension], [FileName], [UploadedBy], [UploadedDate], [Status], [CanDelete], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [BackgroundId]) VALUES (9, 1, N'CurrentJob', N'/Content/images/about/', N'.jpg', N'quocgia', NULL, NULL, N'ACT', 0, N'admin', CAST(N'2017-03-10 16:25:00.000' AS DateTime), NULL, NULL, N'6')
INSERT [dbo].[TeacherMemory] ([Id], [TeacherId], [Type], [URL], [FileExtension], [FileName], [UploadedBy], [UploadedDate], [Status], [CanDelete], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [BackgroundId]) VALUES (10, 1, N'Student', N'~/Content/images/students/', N'.jpg', N'phuonglan', NULL, NULL, N'ACT', 0, N'admin', CAST(N'2017-03-13 09:38:00.000' AS DateTime), NULL, NULL, NULL)
INSERT [dbo].[TeacherMemory] ([Id], [TeacherId], [Type], [URL], [FileExtension], [FileName], [UploadedBy], [UploadedDate], [Status], [CanDelete], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [BackgroundId]) VALUES (11, 1, N'Student', N'~/Content/images/students/', N'.jpg', N'phuongngoc', NULL, NULL, N'ACT', 0, N'admin', CAST(N'2017-03-13 09:38:00.000' AS DateTime), NULL, NULL, NULL)
INSERT [dbo].[TeacherMemory] ([Id], [TeacherId], [Type], [URL], [FileExtension], [FileName], [UploadedBy], [UploadedDate], [Status], [CanDelete], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [BackgroundId]) VALUES (12, 1, N'Student', N'~/Content/images/students/', N'.jpg', N'phuongthao', NULL, NULL, N'ACT', 0, N'admin', CAST(N'2017-03-13 09:38:00.000' AS DateTime), NULL, NULL, NULL)
INSERT [dbo].[TeacherMemory] ([Id], [TeacherId], [Type], [URL], [FileExtension], [FileName], [UploadedBy], [UploadedDate], [Status], [CanDelete], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [BackgroundId]) VALUES (13, 1, N'Student', N'~/Content/images/students/', N'.jpg', N'vuminhnga', NULL, NULL, N'ACT', 0, N'admin', CAST(N'2017-03-13 09:38:00.000' AS DateTime), NULL, NULL, NULL)
INSERT [dbo].[TeacherMemory] ([Id], [TeacherId], [Type], [URL], [FileExtension], [FileName], [UploadedBy], [UploadedDate], [Status], [CanDelete], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [BackgroundId]) VALUES (14, 1, N'MyClass', N'~/Content/images/classes/', N'.jpg', N'class-22', NULL, NULL, NULL, 0, N'admin', CAST(N'2017-03-13 09:59:00.000' AS DateTime), NULL, NULL, NULL)
INSERT [dbo].[TeacherMemory] ([Id], [TeacherId], [Type], [URL], [FileExtension], [FileName], [UploadedBy], [UploadedDate], [Status], [CanDelete], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [BackgroundId]) VALUES (15, 1, N'MyClass', N'~/Content/images/classes/', N'.jpg', N'class-31', NULL, NULL, NULL, 0, N'admin', CAST(N'2017-03-13 09:59:00.000' AS DateTime), NULL, NULL, NULL)
INSERT [dbo].[TeacherMemory] ([Id], [TeacherId], [Type], [URL], [FileExtension], [FileName], [UploadedBy], [UploadedDate], [Status], [CanDelete], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [BackgroundId]) VALUES (16, 1, N'MyClass', N'~/Content/images/classes/', N'.jpg', N'class-42', NULL, NULL, NULL, 0, N'admin', CAST(N'2017-03-13 09:59:00.000' AS DateTime), NULL, NULL, NULL)
INSERT [dbo].[TeacherMemory] ([Id], [TeacherId], [Type], [URL], [FileExtension], [FileName], [UploadedBy], [UploadedDate], [Status], [CanDelete], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [BackgroundId]) VALUES (17, 1, N'MyClass', N'~/Content/images/classes/', N'.png', N'class-8', NULL, NULL, NULL, 0, N'admin', CAST(N'2017-03-13 09:59:00.000' AS DateTime), NULL, NULL, NULL)
INSERT [dbo].[TeacherMemory] ([Id], [TeacherId], [Type], [URL], [FileExtension], [FileName], [UploadedBy], [UploadedDate], [Status], [CanDelete], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [BackgroundId]) VALUES (18, 1, N'MyClass', N'~/Content/images/classes/', N'.jpg', N'class1', NULL, NULL, NULL, 0, N'admin', CAST(N'2017-03-13 09:59:00.000' AS DateTime), NULL, NULL, NULL)
INSERT [dbo].[TeacherMemory] ([Id], [TeacherId], [Type], [URL], [FileExtension], [FileName], [UploadedBy], [UploadedDate], [Status], [CanDelete], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [BackgroundId]) VALUES (19, 1, N'MyClass', N'~/Content/images/classes/', N'.png', N'class-7', NULL, NULL, NULL, 0, N'admin', CAST(N'2017-03-13 09:59:00.000' AS DateTime), NULL, NULL, NULL)
INSERT [dbo].[TeacherMemory] ([Id], [TeacherId], [Type], [URL], [FileExtension], [FileName], [UploadedBy], [UploadedDate], [Status], [CanDelete], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [BackgroundId]) VALUES (20, 1, N'MyClass', N'~/Content/images/classes/', N'.jpg', N'class-5', NULL, NULL, NULL, 0, N'admin', CAST(N'2017-03-13 09:59:00.000' AS DateTime), NULL, NULL, NULL)
INSERT [dbo].[TeacherMemory] ([Id], [TeacherId], [Type], [URL], [FileExtension], [FileName], [UploadedBy], [UploadedDate], [Status], [CanDelete], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [BackgroundId]) VALUES (21, 1, N'MyClass', N'~/Content/images/classes/', N'.jpg', N'class-7', NULL, NULL, NULL, 0, N'admin', CAST(N'2017-03-13 09:59:00.000' AS DateTime), NULL, NULL, NULL)
INSERT [dbo].[TeacherDelegateStudent] ([StudentId], [TeacherId], [Name], [Topic], [SupervisionType], [Time], [Degree], [Status], [CanDelete], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (1, 1, N'Nguyễn Phương Lan', N'Compare the twoEnglish verbals: gerund and to – infinitive', N'University', N'2007', N'BA-AP', N'ACT', 0, N'admin', CAST(N'2017-03-13 09:38:00.000' AS DateTime), NULL, NULL)
INSERT [dbo].[TeacherDelegateStudent] ([StudentId], [TeacherId], [Name], [Topic], [SupervisionType], [Time], [Degree], [Status], [CanDelete], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (2, 1, N'Phan Thị Phương Ngọc', N'Is it true that politeness and indirectness are closely related to each other?', N'University', N'2008', N'BA-AP', N'ACT', 0, N'admin', CAST(N'2017-03-13 09:38:00.000' AS DateTime), NULL, NULL)
INSERT [dbo].[TeacherDelegateStudent] ([StudentId], [TeacherId], [Name], [Topic], [SupervisionType], [Time], [Degree], [Status], [CanDelete], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (3, 1, N'Nguyễn Phương Thảo', N'A small-scale research on English and Vietnamese sentence classification based on their structure', N'University', N'2009', N'BA-AP', N'ACT', 0, N'admin', CAST(N'2017-03-13 09:38:00.000' AS DateTime), NULL, NULL)
INSERT [dbo].[TeacherDelegateStudent] ([StudentId], [TeacherId], [Name], [Topic], [SupervisionType], [Time], [Degree], [Status], [CanDelete], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (4, 1, N'Vũ Minh Nga', N'Some differences between English and Vietnamese compound noun', N'University', N'2010', N'BA-AP', N'ACT', 0, N'admin', CAST(N'2017-03-13 09:38:00.000' AS DateTime), NULL, NULL)
INSERT [dbo].[TeacherStudies] ([Id], [TeacherId], [Title], [Description], [Type], [Status], [CanDelete], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [Year]) VALUES (1, 1, N'English Linguistics', N'<strong>Linguistics</strong> is the scientific study of language, specifically of language form,
                                    language meaning, and language in context. <br />The earliest activities in the description of language have
                                    been attributed to the 4th century BCE Indian grammarian <a href="https://en.wikipedia.org/wiki/P%C4%81%E1%B9%87ini">Pāṇini</a>,
                                    who was an early student of linguistics and wrote a formal description of the Sanskrit
                                    language in his <a href="https://en.wikipedia.org/wiki/Linguistics#cite_note-6">Aṣṭādhyāyī</a>.', N'ResearchInterests', N'ACT', 0, N'admin', CAST(N'2017-03-10 16:32:00.000' AS DateTime), NULL, NULL, N'2017')
INSERT [dbo].[TeacherStudies] ([Id], [TeacherId], [Title], [Description], [Type], [Status], [CanDelete], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [Year]) VALUES (2, 1, N'The studies of Japan', N'Japanese studies or Japan studies (sometimes Japanology in Europe) is a division
                                    of area studies or East Asian studies involved in social sciences and humanities research on Japan.
                                    It incorporates fields such as the study of Japanese language, culture, history, literature,
                                    art, music, and science. Its roots may be traced back to the Dutch at Dejima, Nagasaki in the
                                    Edo period. The foundation of the Asiatic Society of Japan at Yokohama in 1872 by men such as
                                    Ernest Satow and Frederick Victor Dickins was an important event in the development of Japanese
                                    studies as an academic discipline.', N'ResearchInterests', N'ACT', 0, N'admin', CAST(N'2017-03-10 16:32:00.000' AS DateTime), NULL, NULL, N'2017')
INSERT [dbo].[TeacherStudies] ([Id], [TeacherId], [Title], [Description], [Type], [Status], [CanDelete], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [Year]) VALUES (3, 1, N'Comparative Linguistics', N'<strong>Linguistics</strong> is the scientific study of language, specifically of language form,
                                    language meaning, and language in context. The earliest activities in the description of language have
                                    been attributed to the 4th century BCE Indian grammarian <a href="https://en.wikipedia.org/wiki/P%C4%81%E1%B9%87ini">Pāṇini</a>,
                                    who was an early student of linguistics and wrote a formal description of the Sanskrit
                                    language in his <a href="https://en.wikipedia.org/wiki/Linguistics#cite_note-6">Aṣṭādhyāyī</a>.', N'ResearchInterests', N'ACT', 0, N'admin', CAST(N'2017-03-10 16:32:00.000' AS DateTime), NULL, NULL, N'2017')
INSERT [dbo].[TeacherResearchWork] ([Id], [TeacherId], [Title], [Description], [Level], [Member], [Time], [Type], [Status], [CanDelete], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (N'1', 1, N'To investigate the way of pronouncing Stress and Intonation from Vietnamese people (An Experimental Research)', NULL, N'VNU', N'Project leader or member', N'2013', N'ResearchProjects', N'ACT', 0, N'admin', CAST(N'2017-03-10 17:07:00.000' AS DateTime), NULL, NULL)
INSERT [dbo].[TeacherResearchWork] ([Id], [TeacherId], [Title], [Description], [Level], [Member], [Time], [Type], [Status], [CanDelete], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (N'10', 1, N'A case study of solutions to some intonation mistakes made by Vietnamese students – A phonetic experimental research', N'International Journal of Language and Linguistics USA;ISSN 2330-0221;Number 3(2);<a href="http://www.sciencepublishinggroup.com/journal/paperinfo.aspx?journalid=501&doi=10.11648/j.ijll.20150302.13">Download here</a>', NULL, NULL, N'2015', N'JournalArticles', N'ACT', 0, N'admin', CAST(N'2017-03-10 17:07:00.000' AS DateTime), NULL, NULL)
INSERT [dbo].[TeacherResearchWork] ([Id], [TeacherId], [Title], [Description], [Level], [Member], [Time], [Type], [Status], [CanDelete], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (N'11', 1, N'Some Vietnamese Viewpoints upon Second Language Acquistion Theories in Language Contact Environment', N'International Journal of Language and Linguistics USA;ISSN 2330-0221;Number 5(2);<a href="http://www.sciencepublishinggroup.com/journal/paperinfo.aspx?journalid=501&doi=10.11648/j.ijll.20150304.15">Download here</a>', NULL, NULL, N'2015', N'JournalArticles', N'ACT', 0, N'admin', CAST(N'2017-03-10 17:07:00.000' AS DateTime), NULL, NULL)
INSERT [dbo].[TeacherResearchWork] ([Id], [TeacherId], [Title], [Description], [Level], [Member], [Time], [Type], [Status], [CanDelete], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (N'12', 1, N'Trying K-W-L Strategy on Teaching Reading Comprehension to Passive Students in Vietnam', N'International Journal of Language and Linguistics USA;ISSN 2330-0221;Number 1(2);<a href="http://www.sciencepublishinggroup.com/journal/paperinfo.aspx?journalid=501&doi=10.11648/j.ijll.20150306.33">Download here</a>', NULL, NULL, N'2016', N'JournalArticles', N'ACT', 0, N'admin', CAST(N'2017-03-10 17:07:00.000' AS DateTime), NULL, NULL)
INSERT [dbo].[TeacherResearchWork] ([Id], [TeacherId], [Title], [Description], [Level], [Member], [Time], [Type], [Status], [CanDelete], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (N'13', 1, N'Pseudonym: Thach Thanh. Doan Thach Bien Office through rhetorical measures', N'Newspaper Writers Association of HCMC;6/2011;<a href="http://nhavantphcm.com.vn/tac-pham-chon-loc/nghien-cuu-phe-binh/van-phong-doan-thach-bien-qua-tu-tu.html">Download here</a>', NULL, NULL, N'2011', N'JournalArticles', N'ACT', 0, N'admin', CAST(N'2017-03-10 17:07:00.000' AS DateTime), NULL, NULL)
INSERT [dbo].[TeacherResearchWork] ([Id], [TeacherId], [Title], [Description], [Level], [Member], [Time], [Type], [Status], [CanDelete], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (N'14', 1, N'The conception of the word "China" from the Japanese martial artist and Confucians, Vietnam, China', N'Journal of Social Sciences and Humanities University of Social Sciences and Humanities - VNU;Number 48', NULL, NULL, N'2010', N'JournalArticles', N'ACT', 0, N'admin', CAST(N'2017-03-10 17:07:00.000' AS DateTime), NULL, NULL)
INSERT [dbo].[TeacherResearchWork] ([Id], [TeacherId], [Title], [Description], [Level], [Member], [Time], [Type], [Status], [CanDelete], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (N'15', 1, N'The word "Trung" in Giri and "Village Carton" of modern Japanese society.', N'Journal of Social Sciences and Humanities University of Social Sciences and Humanities - VNU;Number 59 - 6/2013', NULL, NULL, N'2013', N'JournalArticles', N'ACT', 0, N'admin', CAST(N'2017-03-10 17:07:00.000' AS DateTime), NULL, NULL)
INSERT [dbo].[TeacherResearchWork] ([Id], [TeacherId], [Title], [Description], [Level], [Member], [Time], [Type], [Status], [CanDelete], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (N'16', 1, N'The word "Trung" in the spirit of Bushido, the social structure and methods of administration of Japan', N'Report in Proceedings of international scientific conference "The value of Japan in Asia" 24/10/2008. ;', NULL, NULL, N'2008', N'ConferenceProceedings', N'ACT', 0, N'admin', CAST(N'2017-03-10 17:07:00.000' AS DateTime), NULL, NULL)
INSERT [dbo].[TeacherResearchWork] ([Id], [TeacherId], [Title], [Description], [Level], [Member], [Time], [Type], [Status], [CanDelete], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (N'17', 1, N'Some causes of any service (Fueki) and the transformation of the Japanese haiku because of the influence of culture and Western haiku', N'Report Published Proceedings International Scientific Conference "The modernization of Japanese literature and cultural zone countries kanji" 2010.;', NULL, NULL, N'2010', N'ConferenceProceedings', N'ACT', 0, N'admin', CAST(N'2017-03-10 17:07:00.000' AS DateTime), NULL, NULL)
INSERT [dbo].[TeacherResearchWork] ([Id], [TeacherId], [Title], [Description], [Level], [Member], [Time], [Type], [Status], [CanDelete], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (N'18', 1, N'Overview Japanese ties with Mekong region countries through English bibliographies', N'Report Published Proceedings of International Scientific Conference "Japan and the Mekong region countries - historical relationship" in 2010.;', NULL, NULL, N'2010', N'ConferenceProceedings', N'ACT', 0, N'admin', CAST(N'2017-03-10 17:07:00.000' AS DateTime), NULL, NULL)
INSERT [dbo].[TeacherResearchWork] ([Id], [TeacherId], [Title], [Description], [Level], [Member], [Time], [Type], [Status], [CanDelete], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (N'19', 1, N'Japanese relations - Vietnam: From ideas to assistance', N'Report Published Proceedings International Scientific Conference "40 years of the Vietnam - Japan, achievements and prospects" 2013.;', NULL, NULL, N'2013', N'ConferenceProceedings', N'ACT', 0, N'admin', CAST(N'2017-03-10 17:07:00.000' AS DateTime), NULL, NULL)
INSERT [dbo].[TeacherResearchWork] ([Id], [TeacherId], [Title], [Description], [Level], [Member], [Time], [Type], [Status], [CanDelete], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (N'2', 1, N'Ta-Mun language study in relation to the language of origin south Bahnar', NULL, N'VNU – C2', N' Leader: Prof. Le Khac Cuong<br />
                                    Member: Dr. Tran Thi Thanh Dieu', N'2017', N'ResearchProjects', N'ACT', 0, N'admin', CAST(N'2017-03-10 17:07:00.000' AS DateTime), NULL, NULL)
INSERT [dbo].[TeacherResearchWork] ([Id], [TeacherId], [Title], [Description], [Level], [Member], [Time], [Type], [Status], [CanDelete], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (N'3', 1, N'Second language (English) acquisition and how to improve bilingual ability for Vietnamese people', NULL, N'USSH', N'Dr. Tran Thi Thanh Dieu', N'2017', N'ResearchProjects', N'ACT', 0, N'admin', CAST(N'2017-03-10 17:07:00.000' AS DateTime), NULL, NULL)
INSERT [dbo].[TeacherResearchWork] ([Id], [TeacherId], [Title], [Description], [Level], [Member], [Time], [Type], [Status], [CanDelete], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (N'4', 1, N'<h3>English syllabus specialized in History</h3>
                                <p><strong>Episode 1</strong></p>', N'<p>
                                        Nescius malis eram si malis, elit de officia, quibusdam summis pariatur appellat
                                        se litteris ad legam, irure ubi offendit do te irure nescius comprehenderit,
                                        mandaremus eram ullamco e eu esse malis in officia. Quae vidisse expetendis se
                                        quem litteris ubi despica.
                                    </p>', NULL, NULL, N'2003', N'Books', N'ACT', 0, N'admin', CAST(N'2017-03-10 17:07:00.000' AS DateTime), NULL, NULL)
INSERT [dbo].[TeacherResearchWork] ([Id], [TeacherId], [Title], [Description], [Level], [Member], [Time], [Type], [Status], [CanDelete], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (N'5', 1, N'<h3>English syllabus specialized in History</h3>
                                <p><strong>Episode 2</strong></p>', N'<p>
                                Nescius malis eram si malis, elit de officia, quibusdam summis pariatur appellat
                                se litteris ad legam, irure ubi offendit do te irure nescius comprehenderit,
                                mandaremus eram ullamco e eu esse malis in officia. Quae vidisse expetendis se
                                quem litteris ubi despica.
                            </p>', NULL, NULL, N'2003', N'Books', N'ACT', 0, N'admin', CAST(N'2017-03-10 17:07:00.000' AS DateTime), NULL, NULL)
INSERT [dbo].[TeacherResearchWork] ([Id], [TeacherId], [Title], [Description], [Level], [Member], [Time], [Type], [Status], [CanDelete], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (N'6', 1, N'English language phenomena in the Vietnamese students', N'Glossary school magazine and Encyclopedia ;ISSN 1859-3135;Number 3 (17) May 5', NULL, NULL, N'2012', N'JournalArticles', N'ACT', 0, N'admin', CAST(N'2017-03-10 17:07:00.000' AS DateTime), NULL, NULL)
INSERT [dbo].[TeacherResearchWork] ([Id], [TeacherId], [Title], [Description], [Level], [Member], [Time], [Type], [Status], [CanDelete], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (N'7', 1, N'Phonetic experimental research into the acquisition of English stress through rhythm by Vietnamese students', N'Journal of Science and Technology of Transport <br />
                                    Ho Chi Minh University of transport and communications;ISSN 0866-7020;Number 2-04/ 2012', NULL, NULL, N'2012', N'JournalArticles', N'ACT', 0, N'admin', CAST(N'2017-03-10 17:07:00.000' AS DateTime), NULL, NULL)
INSERT [dbo].[TeacherResearchWork] ([Id], [TeacherId], [Title], [Description], [Level], [Member], [Time], [Type], [Status], [CanDelete], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (N'8', 1, N'How to determine the stress from English to students in Vietnam', N'Language of Life Magazine;ISSN 0868-3409;Number 6 – 06/ 2012', NULL, NULL, N'2012', N'JournalArticles', N'ACT', 0, N'admin', CAST(N'2017-03-10 17:07:00.000' AS DateTime), NULL, NULL)
INSERT [dbo].[TeacherResearchWork] ([Id], [TeacherId], [Title], [Description], [Level], [Member], [Time], [Type], [Status], [CanDelete], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (N'9', 1, N'Verify the location identification methods accented English by experimental phonetics', N'Journal of University of Thu Dau Mot;ISSN 1859-4433;Number 02(5)/ 2012', NULL, NULL, N'2012', N'JournalArticles', N'ACT', 0, N'admin', CAST(N'2017-03-10 17:07:00.000' AS DateTime), NULL, NULL)
