//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassAnnouncement
    {
        public long Id { get; set; }
        public Nullable<long> ClassId { get; set; }
        public string Title { get; set; }
        public string Brief { get; set; }
        public string Type { get; set; }
        public string Value { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> MofidiedOn { get; set; }
    
        public virtual Class Class { get; set; }
    }
}
