//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommonCode
    {
        public string CommonTypeId { get; set; }
        public string CommonId { get; set; }
        public string StrValue1 { get; set; }
        public string StrValue2 { get; set; }
        public string StrValue3 { get; set; }
        public Nullable<decimal> NumValue1 { get; set; }
        public Nullable<decimal> NumValue2 { get; set; }
        public Nullable<bool> CanDelete { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<int> Qty { get; set; }
        public string Type { get; set; }
    }
}
