//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public long Id { get; set; }
        public string CommentType { get; set; }
        public Nullable<long> ParentId { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<long> ObjectLinkID { get; set; }
        public string Level { get; set; }
        public string Content { get; set; }
    
        public virtual Comment Comment1 { get; set; }
        public virtual Comment Comment2 { get; set; }
        public virtual News News { get; set; }
        public virtual User User { get; set; }
    }
}
