//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Library
    {
        public long Id { get; set; }
        public string Type { get; set; }
        public string Title { get; set; }
        public string Brief { get; set; }
        public string Links { get; set; }
        public string Keyword { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public string Images { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> Download { get; set; }
        public string TypeId { get; set; }
    }
}
