//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public News()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public long Id { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string CategoryId { get; set; }
        public string Title { get; set; }
        public string NewsBrief { get; set; }
        public string NewsDetail { get; set; }
        public string CreatedBy { get; set; }
        public string Editor { get; set; }
        public string Links { get; set; }
        public string Keyword { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public string Images { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual User User { get; set; }
    }
}
