//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherMemory
    {
        public long Id { get; set; }
        public long TeacherId { get; set; }
        public string Type { get; set; }
        public string URL { get; set; }
        public string FileExtension { get; set; }
        public string FileName { get; set; }
        public string UploadedBy { get; set; }
        public Nullable<System.DateTime> UploadedDate { get; set; }
        public string Status { get; set; }
        public Nullable<bool> CanDelete { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string BackgroundId { get; set; }
    
        public virtual Teacher Teacher { get; set; }
        public virtual TeacherBackground TeacherBackground { get; set; }
    }
}
