//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LS.Resources.Users
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcesUsers
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        static ResourcesUsers()
        {
            resourceCulture = System.Globalization.CultureInfo.CreateSpecificCulture("en-US");
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LS.Resources.Users.ResourcesUsers", typeof(ResourcesUsers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        public static string User
        {
            get
            {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }

        public static string MyClass
        {
            get
            {
                return ResourceManager.GetString("MyClass", resourceCulture);
            }
        }

        public static string AllSubjects
        {
            get
            {
                return ResourceManager.GetString("AllSubjects", resourceCulture);
            }
        }

        public static string StudentsCanSearch
        {
            get
            {
                return ResourceManager.GetString("StudentsCanSearch", resourceCulture);
            }
        }

        public static string StudentsCanUpdate
        {
            get
            {
                return ResourceManager.GetString("StudentsCanUpdate", resourceCulture);
            }
        }

        public static string ShareAndAnswer
        {
            get
            {
                return ResourceManager.GetString("ShareAndAnswer", resourceCulture);
            }
        }

        public static string Sincerely
        {
            get
            {
                return ResourceManager.GetString("Sincerely", resourceCulture);
            }
        }

        public static string Syllabus
        {
            get
            {
                return ResourceManager.GetString("Syllabus", resourceCulture);
            }
        }

        public static string Books
        {
            get
            {
                return ResourceManager.GetString("Books", resourceCulture);
            }
        }

        public static string Exercise
        {
            get
            {
                return ResourceManager.GetString("Exercise", resourceCulture);
            }
        }

        public static string Document
        {
            get
            {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }

        public static string Schedule
        {
            get
            {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }

        public static string Diligence
        {
            get
            {
                return ResourceManager.GetString("Diligence", resourceCulture);
            }
        }

        public static string CourseScore
        {
            get
            {
                return ResourceManager.GetString("CourseScore", resourceCulture);
            }
        }

        public static string Discuss
        {
            get
            {
                return ResourceManager.GetString("Discuss", resourceCulture);
            }
        }

        public static string Next
        {
            get
            {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }

        public static string OldPassword
        {
            get
            {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }

        public static string NewPassword
        {
            get
            {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }

        public static string Confirm
        {
            get
            {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }

        public static string Change
        {
            get
            {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }

        public static string ChangePassword
        {
            get
            {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }

        public static string Profile
        {
            get
            {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }

        public static string OldAnnoucements
        {
            get
            {
                return ResourceManager.GetString("OldAnnoucements", resourceCulture);
            }
        }

        public static string ReadMore
        {
            get
            {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }

        public static string NewestAnnouncements
        {
            get
            {
                return ResourceManager.GetString("NewestAnnouncements", resourceCulture);
            }
        }

        public static string AnotherAnnouncements
        {
            get
            {
                return ResourceManager.GetString("AnotherAnnouncements", resourceCulture);
            }
        }

        public static string StudyingSubjects
        {
            get
            {
                return ResourceManager.GetString("StudyingSubjects", resourceCulture);
            }
        }

        public static string StudyedSubjects
        {
            get
            {
                return ResourceManager.GetString("StudyedSubjects", resourceCulture);
            }
        }

        public static string Birthday
        {
            get
            {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }

        public static string Primary
        {
            get
            {
                return ResourceManager.GetString("Primary", resourceCulture);
            }
        }

        public static string Reference
        {
            get
            {
                return ResourceManager.GetString("Reference", resourceCulture);
            }
        }

        public static string Extension
        {
            get
            {
                return ResourceManager.GetString("Extension", resourceCulture);
            }
        }

        public static string Extra
        {
            get
            {
                return ResourceManager.GetString("Extra", resourceCulture);
            }
        }

        public static string Obligatory
        {
            get
            {
                return ResourceManager.GetString("Obligatory", resourceCulture);
            }
        }

        public static string Date
        {
            get
            {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }

        public static string Time
        {
            get
            {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }

        public static string Content
        {
            get
            {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }

        public static string Status
        {
            get
            {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }

        public static string NameOfStudent
        {
            get
            {
                return ResourceManager.GetString("NameOfStudent", resourceCulture);
            }
        }

        public static string Score
        {
            get
            {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }

        public static string Total
        {
            get
            {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }

        public static string Base
        {
            get
            {
                return ResourceManager.GetString("Base", resourceCulture);
            }
        }

        public static string DetailClass
        {
            get
            {
                return ResourceManager.GetString("DetailClass", resourceCulture);
            }
        }

        public static string Attachments
        {
            get
            {
                return ResourceManager.GetString("Attachments", resourceCulture);
            }
        }

    }
}