//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LS.Resources
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        static Resources()
        {
            resourceCulture = System.Globalization.CultureInfo.CreateSpecificCulture("en-US");
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LS.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string EnglishLanguage
        {
            get
            {
                return ResourceManager.GetString("EnglishLanguage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Japanese.
        /// </summary>
        public static string JapaneseLanguage
        {
            get
            {
                return ResourceManager.GetString("JapaneseLanguage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Vietnamese.
        /// </summary>
        public static string VietnameseLanguage
        {
            get
            {
                return ResourceManager.GetString("VietnameseLanguage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Welcome to Dr Thanh Dieu &apos;s website !.
        /// </summary>
        public static string Welcome
        {
            get
            {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AboutMe !.
        /// </summary>
        public static string AboutMe
        {
            get
            {
                return ResourceManager.GetString("AboutMe", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Home !.
        /// </summary>
        public static string Home
        {
            get
            {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Introduction !.
        /// </summary>
        public static string Introduction
        {
            get
            {
                return ResourceManager.GetString("Introduction", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ResearchWork !.
        /// </summary>
        public static string ResearchWork
        {
            get
            {
                return ResourceManager.GetString("ResearchWork", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Studies !.
        /// </summary>
        public static string Studies
        {
            get
            {
                return ResourceManager.GetString("Studies", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Announcement!.
        /// </summary>
        public static string Announcement
        {
            get
            {
                return ResourceManager.GetString("Announcement", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Close!.
        /// </summary>
        public static string Close
        {
            get
            {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ComparativeLinguistic !.
        /// </summary>
        public static string ComparativeLinguistic
        {
            get
            {
                return ResourceManager.GetString("ComparativeLinguistic", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Contact !.
        /// </summary>
        public static string Contact
        {
            get
            {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ChangePassword!.
        /// </summary>
        public static string ChangePassword
        {
            get
            {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DelegateStudents!.
        /// </summary>
        public static string DelegateStudents
        {
            get
            {
                return ResourceManager.GetString("DelegateStudents", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to EmailAddress!.
        /// </summary>
        public static string EmailAddress
        {
            get
            {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MyClass
        /// </summary>
        public static string MyClass
        {
            get
            {
                return ResourceManager.GetString("MyClass", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to EnglishLinguistic!.
        /// </summary>
        public static string EnglishLinguistic
        {
            get
            {
                return ResourceManager.GetString("EnglishLinguistic", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to EnglishSkill
        /// </summary>
        public static string EnglishSkill
        {
            get
            {
                return ResourceManager.GetString("EnglishSkill", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to EnglishTeachingMethodology
        /// </summary>
        public static string EnglishTeachingMethodology
        {
            get
            {
                return ResourceManager.GetString("EnglishTeachingMethodology", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ForgotPassword
        /// </summary>
        public static string ForgotPassword
        {
            get
            {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Grammar
        /// </summary>
        public static string Grammar
        {
            get
            {
                return ResourceManager.GetString("Grammar", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to JapaneseCulture
        /// </summary>
        public static string JapaneseCulture
        {
            get
            {
                return ResourceManager.GetString("JapaneseCulture", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to JapaneseLinguistic
        /// </summary>
        public static string JapaneseLinguistic
        {
            get
            {
                return ResourceManager.GetString("JapaneseLinguistic", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to JapaneseLiterature
        /// </summary>
        public static string JapaneseLiterature
        {
            get
            {
                return ResourceManager.GetString("JapaneseLiterature", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to JapanHistory
        /// </summary>
        public static string JapanHistory
        {
            get
            {
                return ResourceManager.GetString("JapanHistory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to JapanStudies
        /// </summary>
        public static string JapanStudies
        {
            get
            {
                return ResourceManager.GetString("JapanStudies", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Logout
        /// </summary>
        public static string Logout
        {
            get
            {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Login
        /// </summary>
        public static string Login
        {
            get
            {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MemoryAndGallery
        /// </summary>
        public static string MemoryAndGallery
        {
            get
            {
                return ResourceManager.GetString("MemoryAndGallery", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OpenPost
        /// </summary>
        public static string OpenPost
        {
            get
            {
                return ResourceManager.GetString("OpenPost", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password
        /// </summary>
        public static string Password
        {
            get
            {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PleaseSignIn
        /// </summary>
        public static string PleaseSignIn
        {
            get
            {
                return ResourceManager.GetString("PleaseSignIn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Profile
        /// </summary>
        public static string Profile
        {
            get
            {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Register
        /// </summary>
        public static string Register
        {
            get
            {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Schedule
        /// </summary>
        public static string Schedule
        {
            get
            {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Survey
        /// </summary>
        public static string Survey
        {
            get
            {
                return ResourceManager.GetString("Survey", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Teaching
        /// </summary>
        public static string Teaching
        {
            get
            {
                return ResourceManager.GetString("Teaching", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Translation
        /// </summary>
        public static string Translation
        {
            get
            {
                return ResourceManager.GetString("Translation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SignIn
        /// </summary>
        public static string SignIn
        {
            get
            {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DR
        /// </summary>
        public static string DR
        {
            get
            {
                return ResourceManager.GetString("DR", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TranThiThanhDieu
        /// </summary>
        public static string TranThiThanhDieu
        {
            get
            {
                return ResourceManager.GetString("TranThiThanhDieu", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Phonology
        /// </summary>
        public static string Phonology
        {
            get
            {
                return ResourceManager.GetString("Phonology", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Morphology
        /// </summary>
        public static string Morphology
        {
            get
            {
                return ResourceManager.GetString("Morphology", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Syntax
        /// </summary>
        public static string Syntax
        {
            get
            {
                return ResourceManager.GetString("Syntax", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Semantic
        /// </summary>
        public static string Semantic
        {
            get
            {
                return ResourceManager.GetString("Semantic", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pragmatic
        /// </summary>
        public static string Pragmatic
        {
            get
            {
                return ResourceManager.GetString("Pragmatic", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to FunctionalGrammar
        /// </summary>
        public static string FunctionalGrammar
        {
            get
            {
                return ResourceManager.GetString("FunctionalGrammar", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to LiteratureLinguistic
        /// </summary>
        public static string LiteratureLinguistic
        {
            get
            {
                return ResourceManager.GetString("LiteratureLinguistic", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TitleHome
        /// </summary>
        public static string TitleHome
        {
            get
            {
                return ResourceManager.GetString("TitleHome", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to GetInTouch
        /// </summary>
        public static string GetInTouch
        {
            get
            {
                return ResourceManager.GetString("GetInTouch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to FollowMe
        /// </summary>
        public static string FollowMe
        {
            get
            {
                return ResourceManager.GetString("FollowUs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Send
        /// </summary>
        public static string Send
        {
            get
            {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Website
        /// </summary>
        public static string Website
        {
            get
            {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PhoneNumber
        /// </summary>
        public static string PhoneNumber
        {
            get
            {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AllRightsReserved
        /// </summary>
        public static string AllRightsReserved
        {
            get
            {
                return ResourceManager.GetString("AllRightsReserved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PrivacyPolicy
        /// </summary>
        public static string PrivacyPolicy
        {
            get
            {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Terms
        /// </summary>
        public static string Terms
        {
            get
            {
                return ResourceManager.GetString("Terms", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Conditions
        /// </summary>
        public static string Conditions
        {
            get
            {
                return ResourceManager.GetString("Conditions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Images
        /// </summary>
        public static string Images
        {
            get
            {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SocialNetwork
        /// </summary>
        public static string SocialNetwork
        {
            get
            {
                return ResourceManager.GetString("SocialNetwork", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to IAm
        /// </summary>
        public static string IAm
        {
            get
            {
                return ResourceManager.GetString("IAm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to University
        /// </summary>
        public static string University
        {
            get
            {
                return ResourceManager.GetString("University", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MoreAboutLecturers
        /// </summary>
        public static string MoreAboutLecturers
        {
            get
            {
                return ResourceManager.GetString("MoreAboutLecturers", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ReadMoreAboutUs
        /// </summary>
        public static string ReadMoreAboutUs
        {
            get
            {
                return ResourceManager.GetString("ReadMoreAboutUs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ThisisMyClasses
        /// </summary>
        public static string ThisisMyClasses
        {
            get
            {
                return ResourceManager.GetString("ThisisMyClasses", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ViewFullPortfolio
        /// </summary>
        public static string ViewFullPortfolio
        {
            get
            {
                return ResourceManager.GetString("ViewFullPortfolio", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to WeAlwaysSatisfyYou
        /// </summary>
        public static string WeAlwaysSatisfyYou
        {
            get
            {
                return ResourceManager.GetString("WeAlwaysSatisfyYou", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Quality
        /// </summary>
        public static string Quality
        {
            get
            {
                return ResourceManager.GetString("Quality", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MoreImportant
        /// </summary>
        public static string MoreImportant
        {
            get
            {
                return ResourceManager.GetString("MoreImportant", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Quality1
        /// </summary>
        public static string Quantity
        {
            get
            {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Diplomas
        /// </summary>
        public static string Diplomas
        {
            get
            {
                return ResourceManager.GetString("Diplomas", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to WorkYears
        /// </summary>
        public static string WorkYears
        {
            get
            {
                return ResourceManager.GetString("WorkYears", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SchoolsTaught
        /// </summary>
        public static string SchoolsTaught
        {
            get
            {
                return ResourceManager.GetString("SchoolsTaught", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Students
        /// </summary>
        public static string Students
        {
            get
            {
                return ResourceManager.GetString("Students", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pictures
        /// </summary>
        public static string Pictures
        {
            get
            {
                return ResourceManager.GetString("Pictures", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Comments
        /// </summary>
        public static string Comments
        {
            get
            {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to IfYouNeed
        /// </summary>
        public static string IfYouNeed
        {
            get
            {
                return ResourceManager.GetString("IfYouNeed", resourceCulture);
            }
        }
    }
}