//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LS.Resources.About
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcesAbout
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        static ResourcesAbout()
        {
            resourceCulture = System.Globalization.CultureInfo.CreateSpecificCulture("en-US");
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LS.Resources.About.ResourcesAbout", typeof(ResourcesAbout).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        public static string AboutMe
        {
            get
            {
                return ResourceManager.GetString("AboutMe", resourceCulture);
            }
        }

        public static string WhoAmI
        {
            get
            {
                return ResourceManager.GetString("WhoAmI", resourceCulture);
            }
        }

        public static string Education
        {
            get
            {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }

        public static string CurrentJob
        {
            get
            {
                return ResourceManager.GetString("CurrentJob", resourceCulture);
            }
        }

        public static string Teaching
        {
            get
            {
                return ResourceManager.GetString("Teaching", resourceCulture);
            }
        }

        public static string Undergraduate
        {
            get
            {
                return ResourceManager.GetString("Undergraduate", resourceCulture);
            }
        }

        public static string Postgraduate
        {
            get
            {
                return ResourceManager.GetString("Postgraduate", resourceCulture);
            }
        }

        public static string Studies
        {
            get
            {
                return ResourceManager.GetString("Studies", resourceCulture);
            }
        }

        public static string ResearchInterests
        {
            get
            {
                return ResourceManager.GetString("ResearchInterests", resourceCulture);
            }
        }

        public static string ResearchWorks
        {
            get
            {
                return ResourceManager.GetString("ResearchWorks", resourceCulture);
            }
        }

        public static string ResearchProjects
        {
            get
            {
                return ResourceManager.GetString("ResearchProjects", resourceCulture);
            }
        }

        public static string Books
        {
            get
            {
                return ResourceManager.GetString("Books", resourceCulture);
            }
        }

        public static string JournalArticles
        {
            get
            {
                return ResourceManager.GetString("JournalArticles", resourceCulture);
            }
        }

        public static string ConferenceProceedings
        {
            get
            {
                return ResourceManager.GetString("ConferenceProceedings", resourceCulture);
            }
        }

        public static string MyClass
        {
            get
            {
                return ResourceManager.GetString("MyClass", resourceCulture);
            }
        }

        public static string LatestClasses
        {
            get
            {
                return ResourceManager.GetString("LatestClasses", resourceCulture);
            }
        }

        public static string TeachedClasses
        {
            get
            {
                return ResourceManager.GetString("TeachedClasses", resourceCulture);
            }
        }

        public static string DelegateStudents
        {
            get
            {
                return ResourceManager.GetString("DelegateStudents", resourceCulture);
            }
        }

        public static string MemoryGallery
        {
            get
            {
                return ResourceManager.GetString("MemoryGallery", resourceCulture);
            }
        }

        public static string Gallery
        {
            get
            {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }

        public static string ThisisMyClasses
        {
            get
            {
                return ResourceManager.GetString("ThisisMyClasses", resourceCulture);
            }
        }

        public static string Unforgettable
        {
            get
            {
                return ResourceManager.GetString("Unforgettable", resourceCulture);
            }
        }

        public static string Schedule
        {
            get
            {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }

        public static string HCM
        {
            get
            {
                return ResourceManager.GetString("HCM", resourceCulture);
            }
        }

        public static string Categories
        {
            get
            {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }

        public static string Video
        {
            get
            {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }

        public static string Tags
        {
            get
            {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }

        public static string ContactUs
        {
            get
            {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }

        public static string Name
        {
            get
            {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }

        public static string Email
        {
            get
            {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }

        public static string Subject
        {
            get
            {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }

        public static string Message
        {
            get
            {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }

        public static string Send
        {
            get
            {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }

        public static string Information
        {
            get
            {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }

        public static string WorkingHours
        {
            get
            {
                return ResourceManager.GetString("WorkingHours", resourceCulture);
            }
        }

        public static string DetailClass
        {
            get
            {
                return ResourceManager.GetString("DetailClass", resourceCulture);
            }
        }
        public static string ClassDescription
        {
            get
            {
                return ResourceManager.GetString("ClassDescription", resourceCulture);
            }
        }

        public static string ClassDetails
        {
            get
            {
                return ResourceManager.GetString("ClassDetails", resourceCulture);
            }
        }

        public static string RecentClasses
        {
            get
            {
                return ResourceManager.GetString("RecentClasses", resourceCulture);
            }
        }

        public static string ShareThis
        {
            get
            {
                return ResourceManager.GetString("ShareThis", resourceCulture);
            }
        }

        public static string PleaseContact
        {
            get
            {
                return ResourceManager.GetString("PleaseContact", resourceCulture);
            }
        }

        public static string WhoCanLearn
        {
            get
            {
                return ResourceManager.GetString("WhoCanLearn", resourceCulture);
            }
        }

        public static string ObtainingSkills
        {
            get
            {
                return ResourceManager.GetString("ObtainingSkills", resourceCulture);
            }
        }

        public static string Status
        {
            get
            {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }

        public static string HowToRegister
        {
            get
            {
                return ResourceManager.GetString("HowToRegister", resourceCulture);
            }
        }

        public static string Degree
        {
            get
            {
                return ResourceManager.GetString("Degree", resourceCulture);
            }
        }

        public static string ThesisTopic
        {
            get
            {
                return ResourceManager.GetString("ThesisTopic", resourceCulture);
            }
        }

        public static string CompletionYear
        {
            get
            {
                return ResourceManager.GetString("CompletionYear", resourceCulture);
            }
        }

        public static string SupervisionType
        {
            get
            {
                return ResourceManager.GetString("SupervisionType", resourceCulture);
            }
        }

        public static string Address
        {
            get
            {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }

        public static string Phone
        {
            get
            {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
    }
}