//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LS.Resources.Posts
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcesPosts
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        static ResourcesPosts()
        {
            resourceCulture = System.Globalization.CultureInfo.CreateSpecificCulture("en-US");
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LS.Resources.Posts.ResourcesPosts", typeof(ResourcesPosts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        public static string Grammar
        {
            get
            {
                return ResourceManager.GetString("Grammar", resourceCulture);
            }
        }

        public static string Author
        {
            get
            {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }

        public static string University
        {
            get
            {
                return ResourceManager.GetString("University", resourceCulture);
            }
        }

        public static string Quote
        {
            get
            {
                return ResourceManager.GetString("Quote", resourceCulture);
            }
        }

        public static string CategoryArchives
        {
            get
            {
                return ResourceManager.GetString("CategoryArchives", resourceCulture);
            }
        }

        public static string Comments
        {
            get
            {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }

        public static string ShareThisPost
        {
            get
            {
                return ResourceManager.GetString("ShareThisPost", resourceCulture);
            }
        }

        public static string ReadMore
        {
            get
            {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }

        public static string Wordpress
        {
            get
            {
                return ResourceManager.GetString("Wordpress", resourceCulture);
            }
        }

        public static string Reply
        {
            get
            {
                return ResourceManager.GetString("Reply", resourceCulture);
            }
        }

        public static string LeaveAReply
        {
            get
            {
                return ResourceManager.GetString("LeaveAReply", resourceCulture);
            }
        }

        public static string Name
        {
            get
            {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }

        public static string Email
        {
            get
            {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }

        public static string Website
        {
            get
            {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }

        public static string AddYourComment
        {
            get
            {
                return ResourceManager.GetString("AddYourComment", resourceCulture);
            }
        }

        public static string Previous
        {
            get
            {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }

        public static string Next
        {
            get
            {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }

        public static string PopularPost
        {
            get
            {
                return ResourceManager.GetString("PopularPost", resourceCulture);
            }
        }

        public static string EnterKeywords
        {
            get
            {
                return ResourceManager.GetString("EnterKeywords", resourceCulture);
            }
        }

        public static string SubmitComment
        {
            get
            {
                return ResourceManager.GetString("SubmitComment", resourceCulture);
            }
        }

        public static string HideAll
        {
            get
            {
                return ResourceManager.GetString("HideAll", resourceCulture);
            }
        }

        public static string MoreQuestion
        {
            get
            {
                return ResourceManager.GetString("MoreQuestion", resourceCulture);
            }
        }

        public static string MoreAns
        {
            get
            {
                return ResourceManager.GetString("MoreAns", resourceCulture);
            }
        }

        public static string PopularSurvey
        {
            get
            {
                return ResourceManager.GetString("PopularSurvey", resourceCulture);
            }
        }

        public static string LatestNews
        {
            get
            {
                return ResourceManager.GetString("LatestNews", resourceCulture);
            }
        }

        public static string OlderNews
        {
            get
            {
                return ResourceManager.GetString("OlderNews", resourceCulture);
            }
        }

        public static string Categories
        {
            get
            {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }

        public static string DetailAnnoucement
        {
            get
            {
                return ResourceManager.GetString("DetailAnnoucement", resourceCulture);
            }
        }

        public static string RecentAnnoucement
        {
            get
            {
                return ResourceManager.GetString("RecentAnnoucement", resourceCulture);
            }
        }

        public static string Category
        {
            get
            {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }

        public static string Surveying
        {
            get
            {
                return ResourceManager.GetString("Surveying", resourceCulture);
            }
        }

        public static string Surveyed
        {
            get
            {
                return ResourceManager.GetString("Surveyed", resourceCulture);
            }
        }

        public static string OldPost
        {
            get
            {
                return ResourceManager.GetString("OldPost", resourceCulture);
            }
        }

        public static string NewPost
        {
            get
            {
                return ResourceManager.GetString("NewPost", resourceCulture);
            }
        }

        public static string AllPosts
        {
            get
            {
                return ResourceManager.GetString("AllPosts", resourceCulture);
            }
        }
        public static string Link
        {
            get
            {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
    }
}